services:
  node:
    image: "node:current-alpine"
    user: "node"
    container_name: node_samier_fabien_cv
    working_dir: /home/node/app
    environment:
      - NODE_ENV=dev
    volumes:
      - ./:/home/node/app
    ports:
      - "3000:3000"
    command: "npm run dev"
